### ISSUE TITLE
Add session variables

### ISSUE THREAD

**Issue by meghanhorton** [CU-WebTech/printmaster#21]
Can we add session variables or some sort of storage? 

When a guinea pig tried it, they dropped the image in the space rather than the drop zone, which lost all of the changes in the page and they had to start over.

**Comment by ezmac** [comment]
Added a feature to store the current meme as localstorage.  

I evaluated using backbone.localstorage, but due to how it likes to key, I wouldn't be able to use it without hacks that would interfere with storing these in a database later.  So for now, I have custom save and load events and trigger save on model change.  there's still a save button, but it essentially does nothing since every change calls save anyway.
